/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(acars_sig_gen.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(20f5237756f5ed1759cc6128331b331e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/custom_modules/acars_sig_gen.h>
// pydoc.h is automatically generated in the build directory
#include <acars_sig_gen_pydoc.h>

void bind_acars_sig_gen(py::module& m)
{

    using acars_sig_gen    = gr::custom_modules::acars_sig_gen;


    py::class_<acars_sig_gen, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<acars_sig_gen>>(m, "acars_sig_gen", D(acars_sig_gen))

        .def(py::init(&acars_sig_gen::make),
           D(acars_sig_gen,make)
        )
        



        ;




}








